### ISSUE TITLE
Waypoint errors

### ISSUE THREAD

**Issue by twokul** [trek/ember-api#11]
Currently [Waypoints](http://imakewebthings.com/waypoints/) warns when you use waypoints on elements that are either fixed or `display:none`.

In this project we apply a _disabled_ waypoint object to views on [insertion](https://github.com/trek/ember-api/blob/933af51a82b390347a1957f57936331de84f4c46/app/mixins/views/has-waypoint.js#L10-L29). The waypoint [becomes enabled](https://github.com/trek/ember-api/blob/933af51a82b390347a1957f57936331de84f4c46/app/mixins/views/has-waypoint.js#L31-L34) when a user toggles a property that shows the view and [disabled](https://github.com/trek/ember-api/blob/933af51a82b390347a1957f57936331de84f4c46/app/mixins/views/has-waypoint.js#L36-L39) when the view is hidden.

Waypoints debug warns on all `display:none` elements, regardless of Waypoint enabled state:
![screen shot 2015-01-03 at 1 45 14 am](https://cloud.githubusercontent.com/assets/1131196/5602082/3597b34e-92ea-11e4-8504-1a86c5b1fe6a.png)

Docs here: http://imakewebthings.com/waypoints/guides/debugging/#display-none

A PR that successfully addressees this issue will:

- [x] Open a PR on https://github.com/imakewebthings/waypoints, referencing this Issue
- [x] Open a PR to update this project's `bower.json` to reference the proposed fix's repo/sha, so we can move forward while working to resolve the above PR
- [x] Help communicate our issue to @imakewebthings in a way that convinces him to merge
- [x] Help get a new version of https://github.com/imakewebthings/waypoints published to bower
- [x] Update this project's `bower.json` to have that new version

(edited by @trek to create todo list for this issue)

**Comment by trek** [comment]
They're not really errors. The waypoints aren't active. We should PR waypoints to not error if the waypoint attached to a `display: none`element is disabled.

**Comment by imakewebthings** [comment]
imakewebthings/waypoints#364 now open for this. @trek, you've checked off the third bullet point by tagging me in the TODO list. Let's see if I can't get a new version cut with this change included by EOD. I'll update here when I do.

**Comment by trek** [comment]
@imakewebthings can we wait a few days? I'm hoping this is a good issue for some new committers!

**Comment by imakewebthings** [comment]
@trek Absolutely.

**Comment by trek** [comment]
resolved by #17
