### ISSUE TITLE
Refactor/Prune CSS

### ISSUE THREAD

**Issue by trek** [trek/ember-api#15]
The CSS is this project is copied from the compiled css from https://github.com/emberjs/website/ and contains waaaay more CSS that in needed to show the docs.

Mostly the CSS from the website is well organized, but it's a bit hard to tell sometimes if some global style does or doesn't need to remain for the API.

a PR that corrects this issue will:

- [x] move the scss files from https://github.com/emberjs/website/ to this project
- [x] convert the scss compiler from Ruby to node
- [x] convert the use of Compass (Ruby only) to http://bourbon.io/
- [x] bring in ember-cli-sass
- [x] issue PRs to update the entire [ember-cli-sass](https://github.com/aexmachina/ember-cli-sass) -> [broccoli-sass](https://github.com/joliss/broccoli-sass) -> node-sass ecosystem to node-sass 2.0 beta, specifying in this project's package json the branch/commit shas until those commits are merged
- [x] implement any mixins Compass provided (e.g. `border-radius`) that Bourbon doesn't give us
- [x] prune any CSS that we don't need for the docs guide
- [x] update the CSS so that `active` class styling goes on `a` and not `li` elements  (which lets us resolve https://github.com/trek/ember-api/pull/10)

**Comment by trek** [comment]
There's some work already spiked on https://github.com/trek/ember-api/tree/styles. Feel free to look at it for an idea of how to start, but then please just toss it away.

**Comment by davidpett** [comment]
Is there a reason to not use autoprefixer instead of mixins from compass or bourbon? (eg. `border-radius`)

**Comment by trek** [comment]
Seems fine, that just means more refactoring of the existing CSS.

**Comment by gregone** [comment]
I would like to help with this, but I'm having issues running the app.

**Comment by trek** [comment]
@gregone... what issues?

**Comment by gregone** [comment]
@trek It turns out I had a bunch of npm issues, didn't have the docs website built, and my ```data``` repo was not named ```ember-data```
This is fixed, but now I'm getting a strange error from the yuidoc parser: 
```
warn: (docparser): Missing item type:  /Users/greghoin/dev/OpenSource/emberjs/ember.js/packages/ember-runtime/tests/suites/suite.js:43
warn: (docparser): 		Define a name for these tests - all modules are prefixed w/ it.
warn: (docparser): Missing item type:  /Users/greghoin/dev/OpenSource/emberjs/ember.js/packages/ember-runtime/tests/suites/suite.js:50
warn: (docparser): 		Invoked to actually run the test - overridden by mixins
info: (yuidoc): Parsed 879 files in 1.39 seconds
ENAMETOOLONG, name too long '/Users/greghoin/dev/OpenSource/gregone/ember-api/tmp/docs_tmp__-VOcDE2dd.tmp/docs/Ember.A Suite can be used to define a reusable set of unit tests that can be

[...]

## Using a Suite

To use a Suite to test your own objects, extend the suite subclass and
define any required methods.  Then call run() on the new subclass.  This
will create an instance of your class and then defining the unit tests..json'
    at Object.fs.openSync (fs.js:438:18)
    at Object.fs.writeFileSync (fs.js:977:15)
    at Object.<anonymous> (/Users/greghoin/dev/OpenSource/gregone/ember-api/node_modules/ember-cli-yuidoc-converter/addon/index.js:230:10)
    at Array.map (native)
    at Object.Tree.read (/Users/greghoin/dev/OpenSource/gregone/ember-api/node_modules/ember-cli-yuidoc-converter/addon/index.js:163:52)
    at /Users/greghoin/dev/OpenSource/gregone/ember-api/node_modules/ember-cli/node_modules/broccoli/lib/builder.js:78:23
    at $$$internal$$tryCatch (/Users/greghoin/dev/OpenSource/gregone/ember-api/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:470:16)
    at $$$internal$$invokeCallback (/Users/greghoin/dev/OpenSource/gregone/ember-api/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:482:17)
    at /Users/greghoin/dev/OpenSource/gregone/ember-api/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1066:13
    at $$rsvp$asap$$flush (/Users/greghoin/dev/OpenSource/gregone/ember-api/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1531:9)
```

**Comment by trek** [comment]
@gregone you're probably missing a cli option. What did you start ember server with?

**Comment by trek** [comment]
There is also no need to run the old ember documentation site at all.

**Comment by gregone** [comment]
```ember server \
--lib-dir=/Users/greghoin/dev/OpenSource/emberjs/ember.js \
--default-index=Ember \
--default-module=ember \
--github-url=https://github.com/emberjs/ember.js \
--environment=production \
--project-name=ember.js \
--execution-dir=/Users/greghoin/dev/OpenSource/emberjs/ember.js/docs
```
it fails similarly with the optional ```--rev=v1.9.1```.

**Comment by trek** [comment]
Ember moved the location of docs in 1.6 or 1.7... they're not in `/Users/greghoin/dev/OpenSource/emberjs/ember.js/docs`, they're in the project root, so that argument is not required.

**Comment by trek** [comment]
You also don't want to run ember-cli in production while you're working, so don't pass an `--environment` option

**Comment by gregone** [comment]
@trek That worked. Thank you!

**Comment by trek** [comment]
@gregone any update on this? It's a blocker to publishing.

**Comment by gregone** [comment]
@trek Lot's of progress, but i'm blocked by the current state of [node-sass](https://github.com/sass/node-sass) for the 2.0 upgrade of broccoli-sass.

**Comment by trek** [comment]
@gregone what's the block? Does node-sass not yet do with what we need, even in beta?

**Comment by gregone** [comment]
@trek they removed the ```renderFile``` method from node-sass's API: 
https://github.com/sass/node-sass/releases/tag/v2.0.0-beta
```node-sass does not write output to disk from code usage. It will deliver the output which user can store in file/data-base or generate in-memory HTTP responses.```. 
I could work around that with fs in broccoli-sass, but I'm not sure if that's an adequate solution

**Comment by trek** [comment]
@gregone ah, yes, I am familiar. The task "issue PRs to update the entire ember-cli-sass -> broccoli-sass -> node-sass ecosystem to node-sass 2.0 beta, specifying in this project's package json the branch/commit shas until those commits are merged" specifically addresses this problem and how to mitigate it so we can move on

**Comment by gregone** [comment]
@trek :+1:

**Comment by gregone** [comment]
@trek thanks! If there are any follow-up tasks, like the "link to top" or the class/module links selected states, let me know.

**Comment by trek** [comment]
I know @rwjblue had some style feedback, but you may have already addressed them. @rwjblue can you review / file issues?
